### PR TITLE
Fixes and cleaning up to Matlab wrapper and C code

### PR DESCRIPTION
**Pull request by beridel**
I cleaned up the Matlab wrapper:
- removed some commented lines
- 2D weights is now no longer downweighted by number of components
- other random cleaning
- Preset cumulative sum to 0 (might have been causing issues if stations were missing)
- Skip cumulative sum for missing stations via weight == 0

### CODE REVIEW

**Review by ebeauce — COMMENTED** [review]
The point in dividing by n_components the weight matrix when it was reshaped by the wrapper is that if the user provided the weight matrix with shape [n_stations x n_templates] such that the weights summed to one for each template, then the weights still sum to one after being reshaped/extended.

Otherwise, I don't have any comments for the rest of the changes :)

**Comment by beridel** [comment]
I figured that's why there was a division by n_components, but I don't think that's the functionality of the python implementation. In any case, I think it makes a bit more sense (at least to me) to have the output "normalized" to the number of seismic traces and not stations.

What do you think?

**Comment by ebeauce** [comment]
It seems that the Python wrapper is not consistent with the Matlab wrapper, in that there is no division by n_components when the matrix is extended. It would be worth adding it. That way, the output is normalized to the number of seismic traces.

**Comment by beridel** [comment]
I think the two simplest options are normalize by the number of traces (so with 5 stations x 3 components, the maximum would be 15), or normalize to 1. The python implementation behaves as the former, which I think is the most straightforward.

Put another way: the correlation coefficient sum should have the same value whether you manually input all the weights (so above example, N_templates x n_components x n_stations), or opt for the more compact version (N_templates x n_stations which then gets extended in the python wrapper).

**Comment by ebeauce** [comment]
I totally agree that the CCs must have the same value whether you input weights for each component or just for each station. I personally like to have CCmax equal to one, but I guess that whatever is fine if the user knows what is the maximum value to expect :)

**Comment by beridel** [comment]
Okay! So should I go ahead and merge?

**Comment by ebeauce** [comment]
Yes !

**Pull request merged**
