### PR TITLE
WIP: not ready to merge yet: Python make

### PR DESCRIPTION
**Pull request by calum-chamberlain**
Another one not yet ready for a merge, but here to show an idea.

This works by calling the Makefile during the python build process - it tries to build both the CPU and GPU code, but doesn't care if it can't build the GPU code (it warns, but doesn't error), but if it can't build the CPU code it will fail.

This works on my Ubuntu machine, but I need to test it on other machines to be confident in it, hence the request not to merge yet!

All the following work on Ubuntu, but should be tested elsewhere:
```bash
python setup.py build
python setup.py install
pip install .
```
If testing these commands you should run:
```bash
rm fast_matched_filter/lib/*.so; rm -r build; rm -r FastMatchedFilter.egg-info
```
between commands to ensure that recompilation happens.

### CODE REVIEW

**Comment by beridel** [comment]
Seems like it builds and installs itself fine on our cluster.

I'm not quite sure what "pip install ." does that python setup.py install doesn't?

```
wbfrank@eofe5:fast_matched_filter$ pip install .
Processing /home/wbfrank/fast_matched_filter
  Requirement already satisfied (use --upgrade to upgrade): FastMatchedFilter==0.0.1 from file:///home/wbfrank/fast_matched_filter in /home/wbfrank/anaconda2/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy in /home/wbfrank/anaconda2/lib/python2.7/site-packages (from FastMatchedFilter==0.0.1)
You are using pip version 8.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by beridel** [comment]
To answer myself: I'm guessing you wanted to try both ways of installing?

**Comment by calum-chamberlain** [comment]
Indeed, the main reason for trying both was to make sure both worked - pip will do more than setup.py install will (it looks for dependencies and downloads them, but setup.py install just checks whether you have them and if you don't it will crash).
The idea being, if pip works, you could list the package on pypi by running:
```bash
python setup.py register -r pypi
python setup.py sdist upload -r pypi
```
Then users can install using:
```bash
pip install FastMatchedFilter # Or whatever name you chose if you want to change the name in the setup.py file
```
The setup.py file would usually have the package maintainers email and name in it too, I added your name, but didn't put your email in - you can/should if you feel it is appropriate.
Then - if it is installable via pip from pypi, EQcorrscan can require it as a dependency and it would get installed alongside EQcorrscan when people installed that (very selfish desires!).

**Comment by beridel** [comment]
Hah, so you're saying I should merge the pull request and register it on pypi so you can start using it right away in EQcorrscan? ;)

**Comment by calum-chamberlain** [comment]
Not quite, but maybe sometime, when you are ready/happy to...
It would also make it easier for people in general to get hold of the code and use it - not that downloading from github and running make is hard, but people (me) are lazy.

**Review by beridel — APPROVED** [review]
Thumbs up

**Pull request merged**
