### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by calum-chamberlain**
This PR adds a couple of tests to check within a subset of the Kaikoura earthquake dataset, and a synthetic noisy dataset.  This adds the ability to check either CPU or GPU (or both) - tests will not fail if they cannot test the GPU.

These tests use pytest, so this adds a dependency, they do not test Matlab implementations.

Ideally these tests could be run on a Continuous Integration service (like [circleCI](https://circleci.com/)) for the CPU implementation at-least, so that any future updates to the code could be tested before going into the master branch. It is really simple to set-up circleCI, especially for a project like this that has few dependencies. An example of a circleCI config file for a project like this (although yours would be simpler) can be found in the EQcorrscan repository: [circleCI config.yml](https://github.com/eqcorrscan/EQcorrscan/blob/master/.circleci/config.yml) - you would need a simple requirements.txt file as well.

I have designed them so that they should be simple to call, by just running:
```bash
python setup.py test
```
from within the main directory.

For me, these tests fail, but it would be good if someone else could check these to make sure that it isn't just my local install, which may be a little messy (although I have tried to clean it up).

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
PS: pretty sure the second test that checks that the cross-correlation sums are within +/-1 is wrong - should be +/-1 * number of channels (or number of stations). So that needs to be corrected.

**Comment by ebeauce** [comment]
Hello Calum,

In both the CPU and the GPU versions, the CCs are divided by the number of components. Then, we achieve a weighted sum so if the weights sum to one, it's a weighted average and the average CCs should range from -1 to 1.

We don't constrain the weights to sum to one to let the user free to do anything he wants regarding the sum. 

This test should remain as it is now. Note that this test could fail with the CPU version due to the insufficient precision of float numbers to store the cumulative sum of the data, resulting in average CCs that can be slightly larger than one. However, William recently modified the code to store the cumulative sum in double precision, which should be enough to deal with high amplitudes in the data.

Thank you for the circleCI link, I will look at it soon, it seems very helpful.

Eric

**Comment by calum-chamberlain** [comment]
Good to know! In those tests I have just applied equal weight to everything for simplicity.

Agree on the ability to fail due to floating point rounding errors close to the limits, we could set the test to be less strict, possibly by rounding the max and min values to a couple of decimal places?

This is a PR on the branch that William has for the floating-point cumulative sums, so when you merge this it will merge into that branch, it also means that this has the changes William made in it already.  It would be great if you guys could run these tests on your machines? They are not passing for me even with those changes, even after I have (or at-least think I have) cleaned up old versions?

**Comment by calum-chamberlain** [comment]
It looks like [this commit](https://github.com/beridel/fast_matched_filter/commit/a4a2e205f80094c2d12acbecf58290bf05c36194) changed the order of arguments, which I haven't taken into account here, will fix!

**Comment by calum-chamberlain** [comment]
Changed base to `master` now that `CPU_double_sum` has been removed. But I need to rebase this properly - it has double commits.  **Do not merge yet!**

**Comment by beridel** [comment]
Ya, we created quite a messy commit history with Eric. In any case, the current master is what is updated and needs to be double-checked with your tests.

**Comment by calum-chamberlain** [comment]
All good, will update this later today 😸

**Comment by beridel** [comment]
Also, I've been meaning to send you an e-mail: I'll be arriving in NZ with Camille and Suzanne on Oct 30th.  We'll be there until Nov 25th!

**Comment by beridel** [comment]
Also NB: weights are now assigned per component AND station. Perhaps something should be put in where if weights are sent in per station, they're extrapolated to components.

**Comment by calum-chamberlain** [comment]
So this is rebased, but it's not particularly pretty - when we merge it should probably be using the "squash and merge" option (dropdown next to "merge" button should show it) to clean up the history a bit. 

If you want I can start again though and clean everything up?

This branch does increase the size of the repo considerably (because it adds some data for testing): the Kaikoura data I added is 19MB, which is not ideal.  Another option would be to include ObsPy as a dependency for testing and download the data on the fly for tests, but that comes with annoying network issues (the GeoNet FDSN server is notoriously unreliable, but they are working on it), and adds quite a large dependency, which would somewhat spoil the clean simplicity of the project (IMHO).

Note that currently these tests pass for the GPU implementation, but I'm still getting NaNs for the CPU version for the Kaikoura dataset.

**Comment by calum-chamberlain** [comment]
Hey guys, with efforts to correct the issues presented here in #9 I would really recommend merging this PR so that the tests are included in other branches.

**Review by beridel — APPROVED** [review]

**Pull request merged**
